-- Backfill only unchanged starter titles with no genre. Preserve custom genres,
-- renamed songs, personal additions, tags, and all other metadata.
update public.songs as song
set genre = 'Worship'
from (values
  (1, 'Goodness of God'),
  (2, 'Holy Forever'),
  (50, 'Revelation Song'),
  (4, 'Great Are You Lord'),
  (5, 'Build My Life'),
  (51, 'The Heart of Worship'),
  (7, 'Firm Foundation (He Won''t)'),
  (8, 'Living Hope'),
  (9, 'King of Kings'),
  (52, 'Lord I Lift Your Name on High'),
  (11, 'What a Beautiful Name'),
  (12, 'Way Maker'),
  (13, 'How Great Is Our God'),
  (14, '10,000 Reasons (Bless the Lord)'),
  (15, 'Oceans (Where Feet May Fail)'),
  (16, 'This Is Amazing Grace'),
  (17, 'Cornerstone'),
  (18, 'Lord I Need You'),
  (19, 'Reckless Love'),
  (20, 'Battle Belongs'),
  (21, 'Raise a Hallelujah'),
  (53, 'Trading My Sorrows'),
  (54, 'In Christ Alone'),
  (55, 'You Are My All in All'),
  (56, 'As the Deer'),
  (26, 'Praise'),
  (27, 'The Blessing'),
  (28, 'Here I Am to Worship'),
  (29, 'How He Loves'),
  (30, 'Mighty to Save'),
  (31, 'Forever'),
  (32, 'Blessed Be Your Name'),
  (33, 'Our God'),
  (34, 'God of Wonders'),
  (35, 'Open the Eyes of My Heart'),
  (36, 'Shout to the Lord'),
  (37, 'Above All'),
  (38, 'Indescribable'),
  (39, 'Hosanna'),
  (40, 'Amazing Grace (My Chains Are Gone)'),
  (41, 'Glorious Day'),
  (42, 'Good Good Father'),
  (43, 'Christ Is Enough'),
  (44, 'The Stand'),
  (45, 'Every Praise'),
  (57, 'Days of Elijah'),
  (47, 'Promises'),
  (48, 'See a Victory'),
  (49, 'I Speak Jesus'),
  (58, 'How Great Thou Art'),
  (59, 'Great Is Thy Faithfulness'),
  (60, 'Blessed Assurance'),
  (61, 'It Is Well with My Soul'),
  (62, 'Holy, Holy, Holy'),
  (63, 'To God Be the Glory'),
  (64, 'What a Friend We Have in Jesus'),
  (65, 'The Old Rugged Cross'),
  (66, 'Because He Lives'),
  (67, 'I Surrender All')
) as starter(id, title)
where song.id = starter.id and song.title = starter.title
  and (song.genre is null or btrim(song.genre) = '');
