create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.content_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

grant select on public.content_admins to authenticated;
grant all on public.content_admins to service_role;

alter table public.content_admins enable row level security;

create policy "Users can read their own admin membership"
  on public.content_admins for select
  to authenticated
  using (user_id = auth.uid());

create or replace function public.is_content_admin(_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.content_admins
    where user_id = _user_id
  )
$$;

create table public.songs (
  id integer generated by default as identity primary key,
  title text not null check (length(btrim(title)) > 0),
  artist text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select on public.songs to anon, authenticated;
grant insert, update, delete on public.songs to authenticated;
grant all on public.songs to service_role;

alter table public.songs enable row level security;

create policy "Songs are publicly readable"
  on public.songs for select
  to anon, authenticated
  using (true);

create policy "Content admins can insert songs"
  on public.songs for insert
  to authenticated
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can update songs"
  on public.songs for update
  to authenticated
  using (public.is_content_admin(auth.uid()))
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can delete songs"
  on public.songs for delete
  to authenticated
  using (public.is_content_admin(auth.uid()));

create trigger songs_set_updated_at
  before update on public.songs
  for each row execute function public.set_updated_at();

create table public.charades_categories (
  id integer generated by default as identity primary key,
  slug text not null unique check (length(btrim(slug)) > 0),
  label text not null check (length(btrim(label)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select on public.charades_categories to anon, authenticated;
grant insert, update, delete on public.charades_categories to authenticated;
grant all on public.charades_categories to service_role;

alter table public.charades_categories enable row level security;

create policy "Charades categories are publicly readable"
  on public.charades_categories for select
  to anon, authenticated
  using (true);

create policy "Content admins can insert categories"
  on public.charades_categories for insert
  to authenticated
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can update categories"
  on public.charades_categories for update
  to authenticated
  using (public.is_content_admin(auth.uid()))
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can delete categories"
  on public.charades_categories for delete
  to authenticated
  using (public.is_content_admin(auth.uid()));

create trigger charades_categories_set_updated_at
  before update on public.charades_categories
  for each row execute function public.set_updated_at();

create table public.charades_prompts (
  id integer generated by default as identity primary key,
  category_id integer not null references public.charades_categories(id) on delete restrict,
  title text not null check (length(btrim(title)) > 0),
  detail text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select on public.charades_prompts to anon, authenticated;
grant insert, update, delete on public.charades_prompts to authenticated;
grant all on public.charades_prompts to service_role;

alter table public.charades_prompts enable row level security;

create policy "Charades prompts are publicly readable"
  on public.charades_prompts for select
  to anon, authenticated
  using (true);

create policy "Content admins can insert prompts"
  on public.charades_prompts for insert
  to authenticated
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can update prompts"
  on public.charades_prompts for update
  to authenticated
  using (public.is_content_admin(auth.uid()))
  with check (public.is_content_admin(auth.uid()));

create policy "Content admins can delete prompts"
  on public.charades_prompts for delete
  to authenticated
  using (public.is_content_admin(auth.uid()));

create trigger charades_prompts_set_updated_at
  before update on public.charades_prompts
  for each row execute function public.set_updated_at();

create table public.saved_games (
  id integer generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text,
  game_type text not null check (game_type in ('bingo', 'charades', 'singing-bee')),
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select, insert, update, delete on public.saved_games to authenticated;
grant all on public.saved_games to service_role;

alter table public.saved_games enable row level security;

create policy "Owners can read their saved games"
  on public.saved_games for select
  to authenticated
  using (owner_id = auth.uid());

create policy "Owners can create their saved games"
  on public.saved_games for insert
  to authenticated
  with check (owner_id = auth.uid());

create policy "Owners can update their saved games"
  on public.saved_games for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy "Owners can delete their saved games"
  on public.saved_games for delete
  to authenticated
  using (owner_id = auth.uid());

create trigger saved_games_set_updated_at
  before update on public.saved_games
  for each row execute function public.set_updated_at();

insert into public.songs (id, title, artist) values
  (1, 'Goodness of God', 'Bethel Music / Jenn Johnson'),
  (2, 'Holy Forever', 'Chris Tomlin'),
  (3, 'Gratitude', 'Brandon Lake'),
  (4, 'Great Are You Lord', 'All Sons & Daughters'),
  (5, 'Build My Life', 'Pat Barrett'),
  (6, 'Trust in God', 'Elevation Worship'),
  (7, 'Firm Foundation (He Won''t)', 'Cody Carnes'),
  (8, 'Living Hope', 'Phil Wickham'),
  (9, 'King of Kings', 'Hillsong Worship'),
  (10, 'Who Else', 'Gateway Worship'),
  (11, 'What a Beautiful Name', 'Hillsong Worship'),
  (12, 'Way Maker', 'Sinach'),
  (13, 'How Great Is Our God', 'Chris Tomlin'),
  (14, '10,000 Reasons (Bless the Lord)', 'Matt Redman'),
  (15, 'Oceans (Where Feet May Fail)', 'Hillsong UNITED'),
  (16, 'This Is Amazing Grace', 'Phil Wickham'),
  (17, 'Cornerstone', 'Hillsong Worship'),
  (18, 'Lord I Need You', 'Matt Maher'),
  (19, 'Reckless Love', 'Cory Asbury'),
  (20, 'Battle Belongs', 'Phil Wickham'),
  (21, 'Raise a Hallelujah', 'Bethel Music'),
  (22, 'House of the Lord', 'Phil Wickham'),
  (23, 'Same God', 'Elevation Worship'),
  (24, 'Graves Into Gardens', 'Elevation Worship'),
  (25, 'Egypt', 'Bethel Music / Cory Asbury'),
  (26, 'Praise', 'Elevation Worship'),
  (27, 'The Blessing', 'Kari Jobe / Elevation Worship'),
  (28, 'Here I Am to Worship', 'Tim Hughes'),
  (29, 'How He Loves', 'David Crowder Band'),
  (30, 'Mighty to Save', 'Hillsong Worship'),
  (31, 'Forever', 'Chris Tomlin'),
  (32, 'Blessed Be Your Name', 'Matt Redman'),
  (33, 'Our God', 'Chris Tomlin'),
  (34, 'God of Wonders', 'Third Day'),
  (35, 'Open the Eyes of My Heart', 'Paul Baloche'),
  (36, 'Shout to the Lord', 'Darlene Zschech'),
  (37, 'Above All', 'Michael W. Smith'),
  (38, 'Indescribable', 'Chris Tomlin'),
  (39, 'Hosanna', 'Hillsong UNITED'),
  (40, 'Amazing Grace (My Chains Are Gone)', 'Chris Tomlin')
on conflict (id) do update
  set title = excluded.title,
      artist = excluded.artist;

select setval(pg_get_serial_sequence('public.songs', 'id'), 40, true);

insert into public.charades_categories (id, slug, label) values
  (1, 'bible', 'Bible'),
  (2, 'songs', 'Songs'),
  (3, 'church', 'Church')
on conflict (id) do update
  set slug = excluded.slug,
      label = excluded.label;

select setval(pg_get_serial_sequence('public.charades_categories', 'id'), 3, true);