-- Minimal shared song metadata. Unknown values stay NULL; do not guess BPM/year.
alter table public.songs
  add column genre text check (genre is null or length(btrim(genre)) between 1 and 80),
  add column tags text[] not null default '{}' check (cardinality(tags) <= 20 and array_position(tags, null) is null),
  add column release_year integer check (release_year between 1000 and 2100),
  add column bpm numeric(5,2) check (bpm > 0 and bpm <= 400);

-- Preferences belong to a person, never to the publicly readable song row.
create table public.song_ratings (
  id integer generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  song_id integer not null references public.songs(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner_id, song_id)
);

create table public.setlists (
  id integer generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (length(btrim(name)) between 1 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.setlist_items (
  id integer generated by default as identity primary key,
  setlist_id integer not null references public.setlists(id) on delete cascade,
  song_id integer not null references public.songs(id) on delete restrict,
  position integer not null check (position >= 0),
  -- Deferred so a transaction can swap two positions without a temporary collision.
  unique (setlist_id, position) deferrable initially deferred
);

create index song_ratings_song_id_idx on public.song_ratings(song_id);
create index setlists_owner_id_idx on public.setlists(owner_id);
create index setlist_items_song_id_idx on public.setlist_items(song_id);

alter table public.song_ratings enable row level security;
alter table public.setlists enable row level security;
alter table public.setlist_items enable row level security;

create policy "Owners manage their song ratings" on public.song_ratings
  for all to authenticated using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
create policy "Owners manage their setlists" on public.setlists
  for all to authenticated using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
create policy "Owners manage their setlist items" on public.setlist_items
  for all to authenticated
  using (exists (select 1 from public.setlists where id = setlist_id and owner_id = (select auth.uid())))
  with check (exists (select 1 from public.setlists where id = setlist_id and owner_id = (select auth.uid())));

revoke all on public.song_ratings, public.setlists, public.setlist_items from anon, authenticated;
grant select, insert, update, delete on public.song_ratings, public.setlists, public.setlist_items to authenticated;
grant all on public.song_ratings, public.setlists, public.setlist_items to service_role;
grant usage, select on sequence public.song_ratings_id_seq, public.setlists_id_seq, public.setlist_items_id_seq to authenticated, service_role;

create trigger song_ratings_set_updated_at before update on public.song_ratings
  for each row execute function public.set_updated_at();
create trigger setlists_set_updated_at before update on public.setlists
  for each row execute function public.set_updated_at();
